---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: washere-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  # Not specified = default :-)
  # storageClassName: your-special-storage-class